<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <OutputType>WinExe</OutputType>
    <TargetFramework>net8.0-windows</TargetFramework>
    <RootNamespace>Koncoročný_projekt__RPG_game</RootNamespace>
    <Nullable>enable</Nullable>
    <ImplicitUsings>enable</ImplicitUsings>
    <UseWPF>true</UseWPF>
  </PropertyGroup>

  <ItemGroup>
    <Compile Remove="Images\Blocks\NPCs\**" />
    <Compile Remove="Images\Walls\**" />
    <EmbeddedResource Remove="Images\Blocks\NPCs\**" />
    <EmbeddedResource Remove="Images\Walls\**" />
    <None Remove="Images\Blocks\NPCs\**" />
    <None Remove="Images\Walls\**" />
    <Page Remove="Images\Blocks\NPCs\**" />
    <Page Remove="Images\Walls\**" />
  </ItemGroup>

  <ItemGroup>
    <None Remove="Images\AGuy.png" />
    <None Remove="Images\Blocks\Buttom_Walls\andezit_tops.png" />
    <None Remove="Images\Blocks\Buttom_Walls\ButtomDoor_closed.png" />
    <None Remove="Images\Blocks\Buttom_Walls\ButtomDoor_opened.png" />
    <None Remove="Images\Blocks\Buttom_Walls\stone_tops.png" />
    <None Remove="Images\Blocks\Buttom_Walls\wood_tops.png" />
    <None Remove="Images\Blocks\Flores\andezit_block.png" />
    <None Remove="Images\Blocks\Flores\stone_block.png" />
    <None Remove="Images\Blocks\Flores\wood_block.png" />
    <None Remove="Images\Blocks\Items\Bloxy_Cola_item.png" />
    <None Remove="Images\Blocks\Items\Krankenwagen_item.png" />
    <None Remove="Images\Blocks\Left_Walls\andezit_sides.png" />
    <None Remove="Images\Blocks\Left_Walls\LeftDoor_closed.png" />
    <None Remove="Images\Blocks\Left_Walls\LeftDoor_opened.png" />
    <None Remove="Images\Blocks\Left_Walls\stone_sides.png" />
    <None Remove="Images\Blocks\Left_Walls\wood_sides.png" />
    <None Remove="Images\Blocks\Right_Walls\RightDoor_closed.png" />
    <None Remove="Images\Blocks\Right_Walls\RightDoor_opened.png" />
    <None Remove="Images\Blocks\Right_Walls\stone_sides.png" />
    <None Remove="Images\Blocks\Right_Walls\wood_sides.png" />
    <None Remove="Images\Blocks\Top_Walls\andezit_tops.png" />
    <None Remove="Images\Blocks\Top_Walls\stone_tops.png" />
    <None Remove="Images\Blocks\Top_Walls\TopDoor_closed.png" />
    <None Remove="Images\Blocks\Top_Walls\TopDoor_opened.png" />
    <None Remove="Images\Blocks\Top_Walls\wood_tops.png" />
    <None Remove="Images\Characters\Player\Player.png" />
    <None Remove="Images\Items\faf\Dragon Boots.png" />
    <None Remove="Images\Items\faf\Dragon Chestplate.png" />
    <None Remove="Images\Items\faf\Dragon Helmet.png" />
    <None Remove="Images\Items\faf\Dragon Leggins.png" />
    <None Remove="Images\Items\faf\Rusty Boots.png" />
    <None Remove="Images\Items\faf\Rusty Chestplate.png" />
    <None Remove="Images\Items\faf\Rusty Helmet.png" />
    <None Remove="Images\Items\faf\Rusty Leggins.png" />
    <None Remove="Images\Items\faf\Steel Boots.png" />
    <None Remove="Images\Items\faf\Steel Chestplate.png" />
    <None Remove="Images\Items\faf\Steel Helmet.png" />
    <None Remove="Images\Items\faf\Steel Leggins.png" />
  </ItemGroup>

  <ItemGroup>
    <Resource Include="Images\Blocks\Buttom_Walls\andezit_tops.png" />
    <Resource Include="Images\Blocks\Buttom_Walls\ButtomDoor_closed.png" />
    <Resource Include="Images\Blocks\Buttom_Walls\ButtomDoor_opened.png" />
    <Resource Include="Images\Blocks\Buttom_Walls\stone_tops.png" />
    <Resource Include="Images\Blocks\Buttom_Walls\wood_tops.png" />
    <Resource Include="Images\Blocks\Flores\andezit_block.png" />
    <Resource Include="Images\Blocks\Flores\stone_block.png" />
    <Resource Include="Images\Blocks\Flores\wood_block.png" />
  </ItemGroup>

  <ItemGroup>
    <Resource Include="Images\Blocks\Items\Bloxy_Cola_item.png" />
    <Resource Include="Images\Blocks\Items\Krankenwagen_item.png" />
    <Resource Include="Images\Blocks\Left_Walls\andezit_sides.png" />
    <Resource Include="Images\Blocks\Left_Walls\LeftDoor_closed.png" />
    <Resource Include="Images\Blocks\Left_Walls\LeftDoor_opened.png" />
    <Resource Include="Images\Blocks\Left_Walls\stone_sides.png" />
    <Resource Include="Images\Blocks\Left_Walls\wood_sides.png" />
    <Resource Include="Images\Blocks\Right_Walls\andezit_sides.png" />
    <Resource Include="Images\Blocks\Right_Walls\RightDoor_closed.png" />
    <Resource Include="Images\Blocks\Right_Walls\RightDoor_opened.png" />
    <Resource Include="Images\Blocks\Right_Walls\stone_sides.png" />
    <Resource Include="Images\Blocks\Right_Walls\wood_sides.png" />
    <Resource Include="Images\Blocks\Top_Walls\andezit_tops.png" />
    <Resource Include="Images\Blocks\Top_Walls\stone_tops.png" />
    <Resource Include="Images\Blocks\Top_Walls\TopDoor_closed.png" />
    <Resource Include="Images\Blocks\Top_Walls\TopDoor_opened.png" />
    <Resource Include="Images\Blocks\Top_Walls\wood_tops.png" />
    <Resource Include="Images\Characters\Player\AGuy.png" />
    <Resource Include="Images\Characters\Player\Player.png" />
    <Resource Include="Images\Items\faf\Dragon Boots.png" />
    <Resource Include="Images\Items\faf\Dragon Chestplate.png" />
    <Resource Include="Images\Items\faf\Dragon Helmet.png" />
    <Resource Include="Images\Items\faf\Dragon Leggins.png" />
    <Resource Include="Images\Items\faf\None.png" />
    <Resource Include="Images\Items\faf\AGuy.png" />
    <Resource Include="Images\Items\faf\Rusty Boots.png" />
    <Resource Include="Images\Items\faf\Rusty Chestplate.png" />
    <Resource Include="Images\Items\faf\Rusty Helmet.png" />
    <Resource Include="Images\Items\faf\Rusty Leggins.png" />
    <Resource Include="Images\Items\faf\Steel Boots.png" />
    <Resource Include="Images\Items\faf\Steel Chestplate.png" />
    <Resource Include="Images\Items\faf\Steel Helmet.png" />
    <Resource Include="Images\Items\faf\Steel Leggins.png" />
  </ItemGroup>

  <ItemGroup>
    <Folder Include="Images\Characters\Enemies\" />
    <Folder Include="Images\Characters\NPC\" />
  </ItemGroup>

</Project>
