<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <OutputType>WinExe</OutputType>
    <TargetFramework>net8.0-windows</TargetFramework>
    <RootNamespace>Koncoročný_projekt__RPG_game</RootNamespace>
    <Nullable>enable</Nullable>
    <ImplicitUsings>enable</ImplicitUsings>
    <UseWPF>true</UseWPF>
  </PropertyGroup>

  <ItemGroup>
    <Compile Remove="Images\Blocks\NPCs\**" />
    <Compile Remove="Images\Walls\**" />
    <EmbeddedResource Remove="Images\Blocks\NPCs\**" />
    <EmbeddedResource Remove="Images\Walls\**" />
    <None Remove="Images\Blocks\NPCs\**" />
    <None Remove="Images\Walls\**" />
    <Page Remove="Images\Blocks\NPCs\**" />
    <Page Remove="Images\Walls\**" />
  </ItemGroup>

  <ItemGroup>
    <None Remove="Images\AGuy.png" />
    <None Remove="Images\Blocks\Buttom_Walls\andezit_tops.png" />
    <None Remove="Images\Blocks\Buttom_Walls\ButtomDoor_closed.png" />
    <None Remove="Images\Blocks\Buttom_Walls\ButtomDoor_opened.png" />
    <None Remove="Images\Blocks\Buttom_Walls\ButtomDoor_room.png" />
    <None Remove="Images\Blocks\Buttom_Walls\stone_tops.png" />
    <None Remove="Images\Blocks\Buttom_Walls\wood_tops.png" />
    <None Remove="Images\Blocks\Flores\andezit_block.png" />
    <None Remove="Images\Blocks\Flores\stone_block.png" />
    <None Remove="Images\Blocks\Flores\wood_block.png" />
    <None Remove="Images\Blocks\Items\Bloxy_Cola_item.png" />
    <None Remove="Images\Blocks\Items\Krankenwagen_item.png" />
    <None Remove="Images\Blocks\Left_Walls\andezit_sides.png" />
    <None Remove="Images\Blocks\Left_Walls\LeftDoor_closed.png" />
    <None Remove="Images\Blocks\Left_Walls\LeftDoor_opened.png" />
    <None Remove="Images\Blocks\Left_Walls\LeftDoor_room.png" />
    <None Remove="Images\Blocks\Left_Walls\stone_sides.png" />
    <None Remove="Images\Blocks\Left_Walls\wood_sides.png" />
    <None Remove="Images\Blocks\Others\Chest_B.png" />
    <None Remove="Images\Blocks\Others\Chest_L.png" />
    <None Remove="Images\Blocks\Others\Chest_R.png" />
    <None Remove="Images\Blocks\Others\Chest_T.png" />
    <None Remove="Images\Blocks\Right_Walls\RightDoor_closed.png" />
    <None Remove="Images\Blocks\Right_Walls\RightDoor_opened.png" />
    <None Remove="Images\Blocks\Right_Walls\RightDoor_room.png" />
    <None Remove="Images\Blocks\Right_Walls\stone_sides.png" />
    <None Remove="Images\Blocks\Right_Walls\wood_sides.png" />
    <None Remove="Images\Blocks\Top_Walls\andezit_tops.png" />
    <None Remove="Images\Blocks\Top_Walls\stone_tops.png" />
    <None Remove="Images\Blocks\Top_Walls\TopDoor_closed.png" />
    <None Remove="Images\Blocks\Top_Walls\TopDoor_opened.png" />
    <None Remove="Images\Blocks\Top_Walls\TopDoor_room.png" />
    <None Remove="Images\Blocks\Top_Walls\wood_tops.png" />
    <None Remove="Images\Characters\Enemies\Bat.png" />
    <None Remove="Images\Characters\Enemies\Dragon.png" />
    <None Remove="Images\Characters\Enemies\Jester.png" />
    <None Remove="Images\Characters\Enemies\Knight.png" />
    <None Remove="Images\Characters\Enemies\Mage.png" />
    <None Remove="Images\Characters\Enemies\Mythical Pig.png" />
    <None Remove="Images\Characters\Enemies\Phoenix.png" />
    <None Remove="Images\Characters\Enemies\Shield Spirit.png" />
    <None Remove="Images\Characters\Enemies\Vampire.png" />
    <None Remove="Images\Characters\NPC\KnightNPC.png" />
    <None Remove="Images\Characters\NPC\Trader.png" />
    <None Remove="Images\Characters\Player\Player.png" />
    <None Remove="Images\Characters\Player\Player_Fight.png" />
    <None Remove="Images\Items\faf\Big Health Potion.png" />
    <None Remove="Images\Items\faf\Damage Potion.png" />
    <None Remove="Images\Items\faf\Dragon Boots.png" />
    <None Remove="Images\Items\faf\Dragon Chestplate.png" />
    <None Remove="Images\Items\faf\Dragon Helmet.png" />
    <None Remove="Images\Items\faf\Dragon Leggins.png" />
    <None Remove="Images\Items\faf\Dragon Sword.png" />
    <None Remove="Images\Items\faf\Dull Blade.png" />
    <None Remove="Images\Items\faf\Excalibur.png" />
    <None Remove="Images\Items\faf\Fire Breath Orb.png" />
    <None Remove="Images\Items\faf\Guardian Amulet.png" />
    <None Remove="Images\Items\faf\Health Potion.png" />
    <None Remove="Images\Items\faf\Mythical Meal.png" />
    <None Remove="Images\Items\faf\Phoenix Feather.png" />
    <None Remove="Images\Items\faf\Rusty Boots.png" />
    <None Remove="Images\Items\faf\Rusty Chestplate.png" />
    <None Remove="Images\Items\faf\Rusty Helmet.png" />
    <None Remove="Images\Items\faf\Rusty Leggins.png" />
    <None Remove="Images\Items\faf\Steel Boots.png" />
    <None Remove="Images\Items\faf\Steel Chestplate.png" />
    <None Remove="Images\Items\faf\Steel Helmet.png" />
    <None Remove="Images\Items\faf\Steel Leggins.png" />
    <None Remove="Images\Items\faf\Steel Sword.png" />
  </ItemGroup>

  <ItemGroup>
    <Resource Include="Images\Blocks\Buttom_Walls\ButtomDoor_closed.png" />
  </ItemGroup>

  <ItemGroup>
    <Resource Include="Images\Blocks\Buttom_Walls\andezit_tops.png" />
    <Resource Include="Images\Blocks\Buttom_Walls\ButtomDoor_opened.png" />
    <Resource Include="Images\Blocks\Buttom_Walls\ButtomDoor_room.png" />
    <Resource Include="Images\Blocks\Buttom_Walls\stone_tops.png" />
    <Resource Include="Images\Blocks\Buttom_Walls\wood_tops.png" />
    <Resource Include="Images\Blocks\Flores\andezit_block.png" />
    <Resource Include="Images\Blocks\Flores\stone_block.png" />
    <Resource Include="Images\Blocks\Flores\wood_block.png" />
  </ItemGroup>

  <ItemGroup>
    <Resource Include="Images\Blocks\Items\Bloxy_Cola_item.png" />
    <Resource Include="Images\Blocks\Items\Krankenwagen_item.png" />
    <Resource Include="Images\Blocks\Left_Walls\andezit_sides.png" />
    <Resource Include="Images\Blocks\Left_Walls\LeftDoor_closed.png" />
    <Resource Include="Images\Blocks\Left_Walls\LeftDoor_opened.png" />
    <Resource Include="Images\Blocks\Left_Walls\LeftDoor_room.png" />
    <Resource Include="Images\Blocks\Left_Walls\stone_sides.png" />
    <Resource Include="Images\Blocks\Left_Walls\wood_sides.png" />
    <Resource Include="Images\Blocks\Others\Chest_B.png" />
    <Resource Include="Images\Blocks\Others\Chest_L.png" />
    <Resource Include="Images\Blocks\Others\Chest_R.png" />
    <Resource Include="Images\Blocks\Others\Chest_T.png" />
    <Resource Include="Images\Blocks\Right_Walls\andezit_sides.png" />
    <Resource Include="Images\Blocks\Right_Walls\RightDoor_closed.png" />
    <Resource Include="Images\Blocks\Right_Walls\RightDoor_opened.png" />
    <Resource Include="Images\Blocks\Right_Walls\RightDoor_room.png" />
    <Resource Include="Images\Blocks\Right_Walls\stone_sides.png" />
    <Resource Include="Images\Blocks\Right_Walls\wood_sides.png" />
    <Resource Include="Images\Blocks\Top_Walls\andezit_tops.png" />
    <Resource Include="Images\Blocks\Top_Walls\stone_tops.png" />
    <Resource Include="Images\Blocks\Top_Walls\TopDoor_closed.png" />
    <Resource Include="Images\Blocks\Top_Walls\TopDoor_opened.png" />
    <Resource Include="Images\Blocks\Top_Walls\TopDoor_room.png" />
    <Resource Include="Images\Blocks\Top_Walls\wood_tops.png" />
    <Resource Include="Images\Characters\Enemies\Bat.png" />
    <Resource Include="Images\Characters\Enemies\Cursed Trader.png" />
    <Resource Include="Images\Characters\Enemies\Dragon.png" />
    <Resource Include="Images\Characters\Enemies\Jester.png" />
    <Resource Include="Images\Characters\Enemies\Knight.png" />
    <Resource Include="Images\Characters\Enemies\Mage.png" />
    <Resource Include="Images\Characters\Enemies\Mythical Pig.png" />
    <Resource Include="Images\Characters\Enemies\Phoenix.png" />
    <Resource Include="Images\Characters\Enemies\Shield Spirit.png" />
    <Resource Include="Images\Characters\Enemies\Vampire.png" />
    <Resource Include="Images\Characters\NPC\KnightNPC.png" />
    <Resource Include="Images\Characters\NPC\Trader.png" />
    <Resource Include="Images\Characters\Player\AGuy.png" />
    <Resource Include="Images\Characters\Player\Player.png" />
    <Resource Include="Images\Characters\Player\Player_Fight.png" />
    <Resource Include="Images\Items\faf\Big Health Potion.png" />
    <Resource Include="Images\Items\faf\Damage Potion.png" />
    <Resource Include="Images\Items\faf\Dragon Boots.png" />
    <Resource Include="Images\Items\faf\Dragon Chestplate.png" />
    <Resource Include="Images\Items\faf\Dragon Helmet.png" />
    <Resource Include="Images\Items\faf\Dragon Leggins.png" />
    <Resource Include="Images\Items\faf\Dragon Sword.png" />
    <Resource Include="Images\Items\faf\Dull Blade.png" />
    <Resource Include="Images\Items\faf\Excalibur.png" />
    <Resource Include="Images\Items\faf\Fire Breath Orb.png" />
    <Resource Include="Images\Items\faf\Guardian Amulet.png" />
    <Resource Include="Images\Items\faf\Health Potion.png" />
    <Resource Include="Images\Items\faf\Mythical Meal.png" />
    <Resource Include="Images\Items\faf\None.png" />
    <Resource Include="Images\Items\faf\AGuy.png" />
    <Resource Include="Images\Items\faf\Phoenix Feather.png" />
    <Resource Include="Images\Items\faf\Rusty Boots.png" />
    <Resource Include="Images\Items\faf\Rusty Chestplate.png" />
    <Resource Include="Images\Items\faf\Rusty Helmet.png" />
    <Resource Include="Images\Items\faf\Rusty Leggins.png" />
    <Resource Include="Images\Items\faf\Steel Boots.png" />
    <Resource Include="Images\Items\faf\Steel Chestplate.png" />
    <Resource Include="Images\Items\faf\Steel Helmet.png" />
    <Resource Include="Images\Items\faf\Steel Leggins.png" />
    <Resource Include="Images\Items\faf\Steel Sword.png" />
  </ItemGroup>

  <ItemGroup>
    <Folder Include="Images\Characters\NPC\" />
    <Folder Include="Saves\DEFAULT\" />
  </ItemGroup>

</Project>
